Django/my_site/core/urls.py
from django.urls import path, reverse
from . import views

app_name = 'core'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name="login"),
    path('register/', views.SignupView.as_view(), name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('<int:user_id>/add_remove_friend/', views.AddRemoveFriend.as_view(), name="add_remove_friend"),
    path('<int:user_id>/edit/', views.ProfileEditView.as_view(), name="profile_edit"),
]

Django/my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/my_site/posts/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views


app_name = 'posts'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name="index"),
    path('posts/create/', views.post_create, name="post_create"),
    path('posts/<int:post_id>/delete/', views.DeletePostView.as_view(), name="post_delete"),
    path('posts/<int:post_id>/delete-post-success/', TemplateView.as_view(template_name='posts/delete_success.html'), name="delete-post-success"),
    path('posts/<int:post_id>/edit/', views.EditPostView.as_view(), name="post_edit"),
    path('posts/<int:post_id>/like/', views.post_like, name="post_like"),
    re_path(r'^posts/(?P<post_id>\w+)/$', views.PostDetail.as_view(), name="post_detail"),
    path('feed/', views.FeedView.as_view(), name="feed"),

]

Django/my_site/posts/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from core.models import CustomUser
from django.urls import reverse


def post_image_path(instance, filename):
    user_id = instance.id
    return "posts/user-{}/{}".format(user_id, filename)


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='posts')
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='posts', blank=True, validators=[FileExtensionValidator(['jpeg', 'jpg', 'png'])])
    date_pub = models.DateTimeField(auto_now_add=True)
    date_edit = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(CustomUser, related_name='users_like_it', blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.pk})

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    @property
    def like_count(self):
        return self.likes.count()

    def __str__(self):
        return "Post from {} with #{}".format(self.author, self.id)


class Comment(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments')
    likes = models.ManyToManyField(CustomUser, related_name='like_comments', blank=True)
    text = models.TextField(max_length=500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    date_pub = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Comment from {} to post #{}".format(self.author, self.post.id)

Django/my_site/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post, Comment


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['description', 'image']
        labels = {
            'description': 'Описание поста',
            'image': 'Ваше фото',
        }

        widgets = {
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Напишите здесь что-нибудь'
                }
            ),
            'image': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise ValidationError("no description :(")
        return description

    def clean_image(self):
        AVAILABLE_EXTENSIONS = ['jpeg', 'jpg', 'png', 'gif']
        image = self.cleaned_data.get('image')
        if image:
            extension = str(image.name).rsplit('.', 1)[-1]
            if not extension in AVAILABLE_EXTENSIONS:
                raise ValidationError('wrong extension! >.<"')
        return image


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Текст комментария"})
        }

Django/my_site/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DeleteView, UpdateView, DetailView

from .forms import PostCreateForm, CommentForm
from .models import Post, Comment


class IndexView(ListView):
    model = Post
    template_name = 'posts/index.html'
    context_object_name = "posts"
    queryset = Post.objects.annotate(likes_count=Count('likes')).order_by('-likes_count')[:10]


class FeedView(ListView):
    model = Post
    template_name = 'posts/index.html'
    context_object_name = "posts"

    def get_queryset(self):
        if self.request.user.is_authenticated:
            queryset = Post.objects.filter(author__in=self.request.user.friends.all()).order_by('-date_pub')[:10]
        else:
            queryset = []
        return queryset


class PostDetail(DetailView):
    model = Post
    comment_form = CommentForm
    pk_url_kwarg = 'post_id'
    template_name = 'posts/post_detail.html'

    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['comments'] = Comment.objects.filter(post__pk=post_id).order_by('-date_pub')[:5]
        context['comment_form'] = self.comment_form
        return self.render_to_response(context)

    def post(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        form = self.comment_form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = self.object
            comment.save()

        context = self.get_context_data(object=self.object)
        context.update({
            'comments': Comment.objects.filter(post__pk=post_id).order_by('-date_pub')[:5],
            'comment_form': self.comment_form,
        })
        return self.render_to_response(context)


@login_required()
def post_create(request):
    template_name = 'posts/post_create.html'
    if request.method == 'GET':
        form = PostCreateForm()
        context = {'form': form}
        return render(request, template_name, context)
    elif request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('posts:post_detail', kwargs={'post_id': post.id}))
        else:
            context = {'form': form}
            return render(request, template_name, context)


class EditPostView(UpdateView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'posts/post_edit.html'
    form_class = PostCreateForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        print(self.request.__dict__)
        if obj.author != self.request.user:
            raise Exception("You are not allowed!")
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('posts:post_detail', args=(post_id,))


class DeletePostView(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'posts/post_delete.html'

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('posts:delete-post-success', args=(post_id,))


def post_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user and request.user.is_authenticated:
        if request.user in post.likes.all():
            like = post.likes.get(pk=request.user.id)
            post.likes.remove(like)
        else:
            post.likes.add(request.user)
            post.save()
    return redirect(request.META.get('HTTP_REFERER'), request)

Django/my_site/posts/templates/posts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/style.css' %}">
    <title>
        {% block title %}
            ADVITO
        {% endblock title %}
    </title>
</head>
<body class="page">
{% block page %}
    {% block header %}
        {% include 'posts/header.html' %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
        {% include 'posts/footer.html' %}
    {% endblock footer %}
{% endblock page %}
</body>
</html>

Django/my_site/posts/templates/posts/delete_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success delete</title>
</head>
<body>
    <h1>DELETE WAS OK!</h1>
</body>
</html>

Django/my_site/posts/templates/posts/footer.html
<footer>
  <p>О НАС</p>
</footer>

Django/my_site/posts/templates/posts/header.html
<header class="header">
  <div class="logo"></div>
  <h1 class="name">
    <a href="">ADVITO</a>
  </h1>
  {% include 'posts/menu.html' %}
</header>

Django/my_site/posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block title %}
    Все посты
{% endblock title %}

{% block content %}
    {% if posts %}
        {% include 'posts/post_list.html' %}
    {% endif %}
{% endblock content %}

Django/my_site/posts/templates/posts/menu.html
<nav class="menu">
  <ul>
    <li><a href="{% url 'posts:index' %}">Главная страница</a></li>
    {% if user.is_authenticated %}
      <li><a href="{% url 'core:profile' user.id %}">Мои Обьявления</a></li>
      <li><a href="{% url 'posts:post_create' %}">Создать объявление</a></li>
      <li><a href="{% url 'core:logout' %}">Выйти</a></li>
    {% else %}
      <li><a href="{% url 'core:register' %}">Зарегистрироваться</a></li>
      <li><a href="{% url 'core:login' %}">Войти</a></li>
    {% endif %}
  </ul>
</nav>

Django/my_site/posts/templates/posts/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post create</title>
</head>
<body>
    <a href="posts/index.html">
            Home
        </a>
    <form action="{% url 'posts:post_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
</body>
</html>

Django/my_site/posts/templates/posts/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post delete</title>
</head>
<body>
    {% if post.author != user %}
        <h1>Вы не можете удалить пост!</h1>
    {% else %}
        <h1>Вы уверены что хотите удалить пост?</h1>
        <form method="post" action="{% url 'posts:post_delete' post.id %}">
            {% csrf_token %}
            <button type="submit">Удалить!!!!111</button>
        </form>
        <a href="{% url 'posts:post_detail' post.id %}">НЕТ</a>
    {% endif %}
</body>
</html>

Django/my_site/posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <H1>{{ post }}</H1>
    <p>Author: {{ post.author }}</p>
    <p>Likes: {{ post.likes.count }}</p>
    <form method="post" action="{% url 'posts:post_like' post.id %}">
        {% csrf_token %}
        <button type="submit">Like ♥</button>
    </form>
    <img src="{{ post.image_url }}">

    {% if comments %}
    <h2>Comments:</h2>
    {% for comment in comments %}
        <p>{{ comment.author }}</p>
        <p>{{ comment.date_pub }}</p>
        <p>{{ comment.text }}</p>
    {% endfor %}
    {% else %}
    <h2>No comments yet. Be first!</h2>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">Добавить комментарий</button>
    </form>
</body>
</html>

Django/my_site/posts/templates/posts/post_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post update</title>
</head>
<body>
    <h1>UPDATE POST</h1>
    <form action="{% url 'posts:post_edit' post.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="OK">
    </form>
</body>
</html>

Django/my_site/posts/templates/posts/post_list.html
<div class="posts">
    <ul class="posts__list">
        {% for post in posts %}
        <li class="posts__item">
            <a href="{% url 'posts:post_detail' post.id %}">{{ post }}</a>
            <p>Author: <a href="{% url 'core:profile' post.author.id %}">{{ post.author }}</a></p>
            <p>Likes: {{ post.likes.count }}</p>
            <p>Dislikes: {{ post.dislikes.count }}</p>
            <form method="post" action="{% url 'posts:post_like' post.id %}">
                {% csrf_token %}
                <button type="submit">Like ♥</button>
            </form>
            <img class="post__image" src="{{ post.image_url }}">
        </li>
        {% endfor %}
    </ul>
</div>