Django/my_site/core/urls.py
from django.urls import path, reverse
from . import views

app_name = 'core'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name="login"),
    path('register/', views.SignupView.as_view(), name="register"),
    path('logout/', views.logout_view, name="logout"),
    path('<int:user_id>/', views.ProfileView.as_view(), name="profile"),
    path('<int:user_id>/add_remove_friend/', views.AddRemoveFriend.as_view(), name="add_remove_friend"),
    path('<int:user_id>/edit/', views.ProfileEditView.as_view(), name="profile_edit"),
]

Django/my_site/my_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django/my_site/posts/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views


app_name = 'posts'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name="index"),
    path('posts/create/', views.post_create, name="post_create"),
    path('posts/<int:post_id>/delete/', views.DeletePostView.as_view(), name="post_delete"),
    path('posts/<int:post_id>/delete-post-success/', TemplateView.as_view(template_name='posts/delete_success.html'), name="delete-post-success"),
    path('posts/<int:post_id>/edit/', views.EditPostView.as_view(), name="post_edit"),
    path('posts/<int:post_id>/like/', views.post_like, name="post_like"),
    re_path(r'^posts/(?P<post_id>\w+)/$', views.PostDetail.as_view(), name="post_detail"),
    path('feed/', views.FeedView.as_view(), name="feed"),

]

Django/my_site/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from .validators import validate_birth_date


def user_avatar_path(instance, filename):
    user_id = instance.id
    return "user_avatars/user-{}/{}".format(user_id, filename)


class CustomUser(AbstractUser):
    birth_date = models.DateField(blank=True, null=True, validators=[validate_birth_date, ])
    about = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to=user_avatar_path)
    friends = models.ManyToManyField('self', blank=True)

    def get_absolute_url(self):
        return reverse('core:profile', kwargs={'user_id': self.pk})

Django/my_site/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.datetime_safe import datetime

from .models import CustomUser


class SignupForm(UserCreationForm):
    birth_date = forms.DateField(label='Дата рождения', input_formats=['%d-%m-%Y'],
                                 widget=forms.DateInput(
                                     attrs={
                                         'class': 'form-control',
                                         'placeholder': 'dd-mm-yyyy',
                                     }))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'birth_date', 'avatar')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError('Введите емейл!')
        if email and CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким адресом уже существует!')
        return email


class UpdateProfileForm(forms.ModelForm):
    birth_date = forms.DateField(label='Дата рождения', input_formats=['%d-%m-%Y'],
                                 widget=forms.SelectDateWidget(
                                     years=range(datetime.now().year - 70, datetime.now().year + 1), attrs={
                                         'class': 'form-control',
                                         'placeholder': 'dd-mm-yyyy',
                                     }))

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email',
                  'birth_date', 'about', 'avatar'
                  ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birth_date'].widget.years = range(datetime.now().year - 70, datetime.now().year + 1)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError('Введите емейл!')
        if email and CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким адресом уже существует!')
        return email

Django/my_site/core/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, UpdateView

from .forms import UpdateProfileForm, SignupForm
from .models import CustomUser


class SignupView(View):
    template_name = 'core/signup.html'
    form = SignupForm

    def get(self, request, *args, **kwargs):
        context = {
            'form': self.form,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('core:profile', kwargs={'user_id': user.id}))
        else:
            return render(request, self.template_name, {
                'form': form,
            })


@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse("posts:index"))


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'core/profile.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'


class ProfileEditView(UpdateView):
    model = CustomUser
    template_name = 'core/edit_profile.html'
    pk_url_kwarg = 'user_id'
    context_object_name = 'profile'
    form_class = UpdateProfileForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj != request.user:
            raise Http404('Вам сюда нельзя! это не ваш профиль! Уходите! >:С')
        return super().dispatch(request, *args, **kwargs)


class AddRemoveFriend(View):
    def post(self, request, user_id, *args, **kwargs):
        profile = get_object_or_404(CustomUser, id=user_id)
        if profile.friends.filter(id=request.user.id).exists():
            friend = profile.friends.get(id=request.user.id)
            profile.friends.remove(friend)
            request.user.friends.remove(profile)
        else:
            profile.friends.add(request.user)
            request.user.friends.add(profile)
        return redirect(request.META.get('HTTP_REFERER'), request)

Django/my_site/core/templates/core/edit_profile.html
{% extends 'posts/base.html' %}

{% block title %}
    Редактирование профиля {{ profile }}
{% endblock title %}


{% block content %}
    <h1>Редактирование профиля {{profile}}</h1>
    <img src="{{profile.avatar.url}}" alt="avatar">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Обновить данные</button>
    </form>

    <h2>Posts:</h2>

{% with posts=profile.posts.all %}
    {% include 'posts/post_list.html' %}
{% endwith %}

{% endblock content %}

Django/my_site/core/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
  <H1>Страница входа</H1>
<!--  <form method="post" action="{% url 'core:login' %}?next={% url 'posts:index' %}">-->
  <form method="post" action="{% url 'core:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
  </form>
</body>
</html>

Django/my_site/core/templates/core/profile.html
{% extends 'posts/base.html' %}

{% block title %}
    Страница пользователя {{ profile }}
{% endblock title %}


{% block content %}
    <h1>Страница пользователя {{ profile }}</h1>
    <h2>{{profile.birth_date|date:"d F Y"}}</h2>
    <h2>About:</h2>
    <p>{{profile.about}}</p>
    {% if user.id == profile.id %}
    <a href="{% url 'core:profile_edit' profile.id %}">Редактировать</a>
    {% else %}
    <form action="{% url 'core:add_remove_friend' profile.id %}" method="post">
        {% csrf_token %}
        {% if profile in user.friends.all %}
            <button type="submit">Удалить из друзей</button>
        {% else %}
            <button type="submit">Добавить в друзья</button>
        {% endif %}
    </form>
    {% endif %}
    <img src="{{profile.avatar.url}}" alt="avatar">
    <h2>Posts:</h2>

{% with posts=profile.posts.all %}
    {% include 'posts/post_list.html' %}
{% endwith %}

{% endblock content %}

Django/my_site/core/templates/core/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация пользователя</title>
</head>
<body>
    <H1>Регистрация пользователя</H1>
    {% if not user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    {% else %}
        <H2>Вы уже зарегистрированы! Вам сюда не надо!!!1</H2>
    {% endif %}
</body>
</html>